# docker-compose.yml (Orquestación de contenedores con PostgreSQL)
version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: twitter_clone_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: twitter_clone
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: twitter_clone_api
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://user:password@db/twitter_clone
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

volumes:
  postgres_data: